// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://emoesgxwvxnmlqsmvqgn.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImVtb2VzZ3h3dnhubWxxc212cWduIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQ2NTcxNzQsImV4cCI6MjA3MDIzMzE3NH0.0sc84CdvbkZNcKrhxM3QIDCnsjZp8IvrMNTjdbBG3vA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});